services:
  postgres:
    image: 'postgres:latest'
    environment:
      # Змініть цей блок на формат ключ-значення (мапа)
      ACTIVE_SPRING_PROFILE: ${ACTIVE_SPRING_PROFILE} # Тепер це мапа!
      POSTGRES_DB: ${DB_${ACTIVE_SPRING_PROFILE}_NAME}
      POSTGRES_PASSWORD: ${DB_${ACTIVE_SPRING_PROFILE}_PASSWORD}
      POSTGRES_USER: ${DB_${ACTIVE_SPRING_PROFILE}_USERNAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      ACTIVE_SPRING_PROFILE: ${ACTIVE_SPRING_PROFILE}
      SPRING_PROFILES_ACTIVE: ${ACTIVE_SPRING_PROFILE}
      DB_HOST: ${DB_${ACTIVE_SPRING_PROFILE}_HOST}
      DB_NAME: ${DB_${ACTIVE_SPRING_PROFILE}_NAME}
      DB_USERNAME: ${DB_${ACTIVE_SPRING_PROFILE}_USERNAME}
      DB_PASSWORD: ${DB_${ACTIVE_SPRING_PROFILE}_PASSWORD}
    ports:
      - '8080:8080'
    depends_on:
      - postgres

volumes:
  postgres_data:

    $env:CURRENT_DB_HOST="postgres"
    $env:CURRENT_DB_NAME=$env:DB_DEV_NAME
    $env:CURRENT_DB_USERNAME=$env:DB_DEV_USERNAME
    $env:CURRENT_DB_PASSWORD=$env:DB_DEV_PASSWORD
    } elseif ($env:ACTIVE_SPRING_PROFILE -eq "prod") {
    $env:CURRENT_DB_HOST="postgres"
    $env:CURRENT_DB_NAME=$env:DB_PROD_NAME
    $env:CURRENT_DB_USERNAME=$env:DB_PROD_USERNAME
    $env:CURRENT_DB_PASSWORD=$env:DB_PROD_PASSWORD
    } else {
  
    $env:CURRENT_DB_HOST="postgres"
    $env:CURRENT_DB_NAME=$env:DB_DEV_NAME
    $env:CURRENT_DB_USERNAME=$env:DB_DEV_USERNAME
    $env:CURRENT_DB_PASSWORD=$env:DB_DEV_PASSWORD
}

  # Запускаємо Docker Compose
  docker compose up
